//! Native backend: emit C, then compile with Clang/LLVM into a real host
//! executable (machino ISA → LLVM → native object code).
//!
//! This replaces the old `--native` path that only ran `wasmtime compile` on
//! linear WASM. The emitted C links against `runtime/native/machino_rt.c`.

use crate::ast::*;
use crate::diag::{Diagnostic, Span};
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Result of a successful native build.
pub struct NativeBuild {
    pub exe_path: PathBuf,
    pub c_path: PathBuf,
    pub ll_path: Option<PathBuf>,
}

fn c_ident(name: &str) -> String {
    let mut out = String::from("mno_");
    for c in name.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' => out.push(c),
            _ => out.push('_'),
        }
    }
    out
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::from("\"");
    for b in s.as_bytes() {
        match *b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(*b as char),
            _ => {
                let _ = write!(out, "\\x{:02x}", b);
            }
        }
    }
    out.push('"');
    out
}

struct Emitter<'a> {
    program: &'a Program,
    out: String,
    structs: HashMap<&'a str, Vec<&'a Param>>,
    enums: HashMap<&'a str, Vec<&'a EnumVariant>>,
    signatures: HashMap<&'a str, (Vec<Type>, Type)>,
    tmp: usize,
    locals: Vec<HashMap<String, Type>>,
    loop_labels: Vec<(String, String)>,
    label_n: usize,
    /// When set, `Var(name)` reads from these C identifiers (ensures shadows).
    ensures_alias: HashMap<String, String>,
}

impl<'a> Emitter<'a> {
    fn new(program: &'a Program) -> Self {
        let mut structs = HashMap::new();
        for s in &program.structs {
            if s.type_params.is_empty() {
                structs.insert(s.name.as_str(), s.fields.iter().collect());
            }
        }
        let mut enums = HashMap::new();
        for e in &program.enums {
            if e.type_params.is_empty() {
                enums.insert(e.name.as_str(), e.variants.iter().collect());
            }
        }
        let mut signatures = HashMap::new();
        for f in &program.functions {
            if f.type_params.is_empty() {
                signatures.insert(
                    f.name.as_str(),
                    (
                        f.params.iter().map(|p| p.ty.clone()).collect(),
                        f.ret.clone(),
                    ),
                );
            }
        }
        Self {
            program,
            out: String::new(),
            structs,
            enums,
            signatures,
            tmp: 0,
            locals: vec![HashMap::new()],
            loop_labels: Vec::new(),
            label_n: 0,
            ensures_alias: HashMap::new(),
        }
    }

    fn fresh(&mut self, prefix: &str) -> String {
        self.tmp += 1;
        format!("{}_{}", prefix, self.tmp)
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        self.label_n += 1;
        format!("{}_{}", prefix, self.label_n)
    }

    fn push_scope(&mut self) {
        self.locals.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.locals.pop();
    }

    fn bind(&mut self, name: &str, ty: Type) {
        self.locals.last_mut().unwrap().insert(name.to_string(), ty);
    }

    fn lookup_ty(&self, name: &str) -> Option<Type> {
        for scope in self.locals.iter().rev() {
            if let Some(t) = scope.get(name) {
                return Some(t.clone());
            }
        }
        None
    }

    fn emit_program(&mut self) -> Result<(), Diagnostic> {
        self.out.push_str("/* generated by machino native (Clang/LLVM) backend */\n");
        self.out.push_str("#include \"machino_rt.h\"\n");
        self.out.push_str("#include <stdint.h>\n\n");

        let reachable = reachable_from_main(self.program);

        // Forward declarations
        for f in &self.program.functions {
            if f.is_extern || !f.type_params.is_empty() || !reachable.contains(&f.name) {
                continue;
            }
            let name = c_ident(&f.name);
            let ret = if f.ret == Type::Unit {
                "void".to_string()
            } else if f.ret == Type::Float {
                "mno_f64".to_string()
            } else {
                "mno_i64".to_string()
            };
            let mut params = String::new();
            for (i, p) in f.params.iter().enumerate() {
                if i > 0 {
                    params.push_str(", ");
                }
                let pt = if p.ty == Type::Float {
                    "mno_f64"
                } else {
                    "mno_i64"
                };
                let _ = write!(params, "{} {}", pt, c_ident(&p.name));
            }
            if f.params.is_empty() {
                params.push_str("void");
            }
            let _ = writeln!(self.out, "{} {}({});", ret, name, params);
        }
        self.out.push('\n');

        let fns: Vec<&Function> = self
            .program
            .functions
            .iter()
            .filter(|f| {
                !f.is_extern && f.type_params.is_empty() && reachable.contains(&f.name)
            })
            .collect();
        for f in fns {
            self.emit_function(f)?;
        }

        self.out.push_str("int main(int argc, char **argv) {\n");
        self.out.push_str("  mno_init(argc, argv);\n");
        self.out.push_str("  mno_main();\n");
        self.out.push_str("  return 0;\n");
        self.out.push_str("}\n");
        Ok(())
    }

    fn emit_function(&mut self, f: &Function) -> Result<(), Diagnostic> {
        let name = c_ident(&f.name);
        let ret = if f.ret == Type::Unit {
            "void"
        } else if f.ret == Type::Float {
            "mno_f64"
        } else {
            "mno_i64"
        };
        let _ = write!(self.out, "{} {}(", ret, name);
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                self.out.push_str(", ");
            }
            let pt = if p.ty == Type::Float {
                "mno_f64"
            } else {
                "mno_i64"
            };
            let _ = write!(self.out, "{} {}", pt, c_ident(&p.name));
        }
        self.out.push_str(") {\n");

        self.locals = vec![HashMap::new()];
        for p in &f.params {
            self.bind(&p.name, p.ty.clone());
        }

        // shadow params for ensures
        let mut shadows: Vec<(String, Type)> = Vec::new();
        if !f.ensures.is_empty() {
            for p in &f.params {
                let sh = format!("__sh_{}", c_ident(&p.name));
                let pt = if p.ty == Type::Float {
                    "mno_f64"
                } else {
                    "mno_i64"
                };
                let _ = writeln!(
                    self.out,
                    "  {} {} = {};",
                    pt,
                    sh,
                    c_ident(&p.name)
                );
                shadows.push((p.name.clone(), p.ty.clone()));
            }
        }

        for c in &f.requires {
            let v = self.emit_expr(&c.expr, Some(&Type::Bool))?;
            let msg = format!(
                "runtime error: contract violation: requires '{}' failed when calling '{}'",
                c.text, f.name
            );
            let _ = writeln!(
                self.out,
                "  if (!({})) mno_fail({});",
                v,
                escape_c_string(&msg)
            );
        }

        let result_tmp = if f.ret != Type::Unit {
            let t = self.fresh("result");
            let pt = if f.ret == Type::Float {
                "mno_f64"
            } else {
                "mno_i64"
            };
            let _ = writeln!(self.out, "  {} {} = 0;", pt, t);
            Some(t)
        } else {
            None
        };
        let exit_lbl = self.fresh_label("exit");

        self.emit_block(&f.body, result_tmp.as_deref(), &f.ret, &exit_lbl)?;

        let _ = writeln!(self.out, "  {}:;", exit_lbl);
        if !f.ensures.is_empty() {
            self.ensures_alias.clear();
            for (name, _) in &shadows {
                self.ensures_alias
                    .insert(name.clone(), format!("__sh_{}", c_ident(name)));
            }
            if let Some(ref r) = result_tmp {
                self.bind("result", f.ret.clone());
                self.ensures_alias
                    .insert("result".into(), r.clone());
            }
            for c in &f.ensures {
                let v = self.emit_expr(&c.expr, Some(&Type::Bool))?;
                let msg = format!(
                    "runtime error: contract violation: ensures '{}' failed in '{}'",
                    c.text, f.name
                );
                let _ = writeln!(
                    self.out,
                    "  if (!({})) mno_fail({});",
                    v,
                    escape_c_string(&msg)
                );
            }
            self.ensures_alias.clear();
        }

        if let Some(r) = result_tmp {
            let _ = writeln!(self.out, "  return {};", r);
        } else {
            self.out.push_str("  return;\n");
        }
        self.out.push_str("}\n\n");
        Ok(())
    }

    fn emit_block(
        &mut self,
        stmts: &[Stmt],
        result_tmp: Option<&str>,
        ret_ty: &Type,
        exit_lbl: &str,
    ) -> Result<(), Diagnostic> {
        self.push_scope();
        for s in stmts {
            self.emit_stmt(s, result_tmp, ret_ty, exit_lbl)?;
        }
        self.pop_scope();
        Ok(())
    }

    fn emit_stmt(
        &mut self,
        stmt: &Stmt,
        result_tmp: Option<&str>,
        ret_ty: &Type,
        exit_lbl: &str,
    ) -> Result<(), Diagnostic> {
        match &stmt.kind {
            StmtKind::Let { name, ty, value } => {
                let inferred = ty.clone().unwrap_or_else(|| self.type_of(value));
                let v = self.emit_expr(value, Some(&inferred))?;
                let cname = c_ident(name);
                let pt = if inferred == Type::Float {
                    "mno_f64"
                } else {
                    "mno_i64"
                };
                let _ = writeln!(self.out, "  {} {} = {};", pt, cname, v);
                self.bind(name, inferred);
            }
            StmtKind::Assign { name, value } => {
                let ty = self
                    .lookup_ty(name)
                    .ok_or_else(|| e_native("unknown variable in assignment", stmt.span))?;
                let v = self.emit_expr(value, Some(&ty))?;
                let _ = writeln!(self.out, "  {} = {};", c_ident(name), v);
            }
            StmtKind::IndexAssign { base, index, value } => {
                let b = self.emit_expr(base, None)?;
                let i = self.emit_expr(index, Some(&Type::Int))?;
                let elem_ty = match self.type_of(base) {
                    Type::Array(e) => *e,
                    _ => Type::Int,
                };
                let v = self.emit_expr(value, Some(&elem_ty))?;
                if elem_ty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_f64_to_bits({});",
                        bits, v
                    );
                    let _ = writeln!(self.out, "  mno_arr_set({}, {}, {});", b, i, bits);
                } else {
                    let _ = writeln!(self.out, "  mno_arr_set({}, {}, {});", b, i, v);
                }
            }
            StmtKind::FieldAssign { base, field, value } => {
                let bty = self.type_of(base);
                let Type::Struct(sname) = bty else {
                    return Err(e_native("field assign on non-struct", stmt.span));
                };
                let idx = self.field_index(&sname, field, stmt.span)?;
                let fty = self.field_type(&sname, field);
                let b = self.emit_expr(base, None)?;
                let v = self.emit_expr(value, Some(&fty))?;
                if fty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_f64_to_bits({});",
                        bits, v
                    );
                    let _ = writeln!(
                        self.out,
                        "  mno_struct_set({}, {}, {});",
                        b, idx, bits
                    );
                } else {
                    let _ = writeln!(self.out, "  mno_struct_set({}, {}, {});", b, idx, v);
                }
            }
            StmtKind::If {
                cond,
                then_body,
                else_body,
            } => {
                let c = self.emit_expr(cond, Some(&Type::Bool))?;
                let _ = writeln!(self.out, "  if ({}) {{", c);
                self.emit_block(then_body, result_tmp, ret_ty, exit_lbl)?;
                self.out.push_str("  } else {\n");
                self.emit_block(else_body, result_tmp, ret_ty, exit_lbl)?;
                self.out.push_str("  }\n");
            }
            StmtKind::While {
                cond,
                invariant: _,
                body,
            } => {
                let cont = self.fresh_label("cont");
                let brk = self.fresh_label("brk");
                self.loop_labels.push((cont.clone(), brk.clone()));
                let _ = writeln!(self.out, "  while (1) {{");
                let c = self.emit_expr(cond, Some(&Type::Bool))?;
                let _ = writeln!(self.out, "    if (!({})) break;", c);
                self.emit_block(body, result_tmp, ret_ty, exit_lbl)?;
                let _ = writeln!(self.out, "    {}:;", cont);
                self.out.push_str("  }\n");
                let _ = writeln!(self.out, "  {}:;", brk);
                self.loop_labels.pop();
            }
            StmtKind::For {
                var,
                start,
                end,
                body,
            } => {
                let cont = self.fresh_label("cont");
                let brk = self.fresh_label("brk");
                self.loop_labels.push((cont.clone(), brk.clone()));
                let s = self.emit_expr(start, Some(&Type::Int))?;
                let e = self.emit_expr(end, Some(&Type::Int))?;
                let vend = self.fresh("end");
                let _ = writeln!(self.out, "  mno_i64 {} = {};", vend, e);
                let _ = writeln!(
                    self.out,
                    "  for (mno_i64 {} = {}; {} < {}; {} = mno_iadd({}, 1)) {{",
                    c_ident(var),
                    s,
                    c_ident(var),
                    vend,
                    c_ident(var),
                    c_ident(var)
                );
                self.push_scope();
                self.bind(var, Type::Int);
                self.emit_block(body, result_tmp, ret_ty, exit_lbl)?;
                self.pop_scope();
                let _ = writeln!(self.out, "    {}:;", cont);
                self.out.push_str("  }\n");
                let _ = writeln!(self.out, "  {}:;", brk);
                self.loop_labels.pop();
            }
            StmtKind::Break => {
                let brk = self
                    .loop_labels
                    .last()
                    .map(|(_, b)| b.clone())
                    .ok_or_else(|| e_native("break outside loop", stmt.span))?;
                let _ = writeln!(self.out, "  goto {};", brk);
            }
            StmtKind::Continue => {
                let cont = self
                    .loop_labels
                    .last()
                    .map(|(c, _)| c.clone())
                    .ok_or_else(|| e_native("continue outside loop", stmt.span))?;
                let _ = writeln!(self.out, "  goto {};", cont);
            }
            StmtKind::Return(None) => {
                let _ = writeln!(self.out, "  goto {};", exit_lbl);
            }
            StmtKind::Return(Some(e)) => {
                let v = self.emit_expr(e, Some(ret_ty))?;
                if let Some(r) = result_tmp {
                    let _ = writeln!(self.out, "  {} = {};", r, v);
                }
                let _ = writeln!(self.out, "  goto {};", exit_lbl);
            }
            StmtKind::Assert(e) => {
                let v = self.emit_expr(e, Some(&Type::Bool))?;
                let _ = writeln!(
                    self.out,
                    "  if (!({})) mno_fail(\"runtime error: assertion failed\");",
                    v
                );
            }
            StmtKind::Expr(e) => {
                let _ = self.emit_expr(e, None)?;
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: Option<&Type>) -> Result<String, Diagnostic> {
        match &expr.kind {
            ExprKind::Int(n) => Ok(format!("{}LL", n)),
            ExprKind::Float(f) => Ok(format!("{:?}", f)),
            ExprKind::Bool(b) => Ok(if *b { "1LL".into() } else { "0LL".into() }),
            ExprKind::Str(s) => {
                let lit = escape_c_string(s);
                let t = self.fresh("str");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_str_from_lit({}, {}LL);",
                    t,
                    lit,
                    s.len()
                );
                Ok(t)
            }
            ExprKind::Var(name) => {
                if let Some(alias) = self.ensures_alias.get(name) {
                    return Ok(alias.clone());
                }
                if let Some(ty) = self.lookup_ty(name) {
                    let _ = ty;
                    return Ok(c_ident(name));
                }
                // unit enum variant
                if let Some(colon) = name.rfind("::") {
                    let en = &name[..colon];
                    let vn = &name[colon + 2..];
                    if let Some(variants) = self.enums.get(en) {
                        let tag = variants
                            .iter()
                            .position(|v| v.name == vn)
                            .ok_or_else(|| e_native("unknown enum variant", expr.span))?;
                        let t = self.fresh("en");
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_enum_new({}LL, 0LL);",
                            t, tag
                        );
                        return Ok(t);
                    }
                }
                // function value — not supported as first-class yet
                if self.signatures.contains_key(name.as_str()) {
                    return Err(e_native(
                        "native backend: first-class function values are not yet supported; call the function directly",
                        expr.span,
                    ));
                }
                Err(e_native(
                    &format!("unknown variable '{}'", name),
                    expr.span,
                ))
            }
            ExprKind::Array(elems) => {
                let t = self.fresh("arr");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_arr_new({}LL);",
                    t,
                    elems.len()
                );
                let elem_ty = elems
                    .first()
                    .map(|e| self.type_of(e))
                    .unwrap_or(Type::Int);
                for (i, e) in elems.iter().enumerate() {
                    let v = self.emit_expr(e, Some(&elem_ty))?;
                    if elem_ty == Type::Float {
                        let bits = self.fresh("bits");
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_f64_to_bits({});",
                            bits, v
                        );
                        let _ = writeln!(self.out, "  mno_arr_set({}, {}LL, {});", t, i, bits);
                    } else {
                        let _ = writeln!(self.out, "  mno_arr_set({}, {}LL, {});", t, i, v);
                    }
                }
                Ok(t)
            }
            ExprKind::Index(base, idx) => {
                let b = self.emit_expr(base, None)?;
                let i = self.emit_expr(idx, Some(&Type::Int))?;
                let t = self.fresh("idx");
                let elem_ty = match self.type_of(base) {
                    Type::Array(e) => *e,
                    Type::Str => Type::Int,
                    _ => Type::Int,
                };
                if matches!(self.type_of(base), Type::Str) {
                    let _ = writeln!(self.out, "  mno_i64 {} = mno_str_at({}, {});", t, b, i);
                } else if elem_ty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_arr_get({}, {});",
                        bits, b, i
                    );
                    let _ = writeln!(
                        self.out,
                        "  mno_f64 {} = mno_bits_to_f64({});",
                        t, bits
                    );
                } else {
                    let _ = writeln!(self.out, "  mno_i64 {} = mno_arr_get({}, {});", t, b, i);
                }
                Ok(t)
            }
            ExprKind::Field(base, field) => {
                let Type::Struct(sname) = self.type_of(base) else {
                    return Err(e_native("field access on non-struct", expr.span));
                };
                let idx = self.field_index(&sname, field, expr.span)?;
                let fty = self.field_type(&sname, field);
                let b = self.emit_expr(base, None)?;
                let t = self.fresh("fld");
                if fty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_struct_get({}, {}LL);",
                        bits, b, idx
                    );
                    let _ = writeln!(
                        self.out,
                        "  mno_f64 {} = mno_bits_to_f64({});",
                        t, bits
                    );
                } else {
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_struct_get({}, {}LL);",
                        t, b, idx
                    );
                }
                Ok(t)
            }
            ExprKind::Un(op, inner) => {
                let ty = self.type_of(inner);
                let v = self.emit_expr(inner, Some(&ty))?;
                let t = self.fresh("un");
                match op {
                    UnOp::Neg if ty == Type::Float => {
                        let _ = writeln!(self.out, "  mno_f64 {} = -({});", t, v);
                    }
                    UnOp::Neg => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_isub(0LL, {});",
                            t, v
                        );
                    }
                    UnOp::Not => {
                        let _ = writeln!(self.out, "  mno_i64 {} = !({});", t, v);
                    }
                }
                Ok(t)
            }
            ExprKind::Bin(op, lhs, rhs) => self.emit_bin(*op, lhs, rhs, expr.span),
            ExprKind::Call(name, _ta, args) => self.emit_call(name, args, expected, expr.span),
            ExprKind::Lambda(_) => Err(e_native(
                "native backend: lambdas are not yet supported; use a named top-level function",
                expr.span,
            )),
            ExprKind::Match(m) => self.emit_match(m, expected, expr.span),
        }
    }

    fn emit_bin(
        &mut self,
        op: BinOp,
        lhs: &Expr,
        rhs: &Expr,
        span: Span,
    ) -> Result<String, Diagnostic> {
        let lt = self.type_of(lhs);
        let rt = self.type_of(rhs);
        let l = self.emit_expr(lhs, Some(&lt))?;
        let r = self.emit_expr(rhs, Some(&rt))?;
        let t = self.fresh("bin");
        use BinOp::*;
        match (&lt, &rt, op) {
            (Type::Str, Type::Str, Add) => {
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_str_concat({}, {});",
                    t, l, r
                );
            }
            (Type::Str, Type::Str, Eq) => {
                let _ = writeln!(self.out, "  mno_i64 {} = mno_str_eq({}, {});", t, l, r);
            }
            (Type::Str, Type::Str, Ne) => {
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = !mno_str_eq({}, {});",
                    t, l, r
                );
            }
            (Type::Float, Type::Float, _) => {
                let fop = match op {
                    Add => "mno_fadd",
                    Sub => "mno_fsub",
                    Mul => "mno_fmul",
                    Div => "mno_fdiv",
                    Eq => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} == {});", t, l, r);
                        return Ok(t);
                    }
                    Ne => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} != {});", t, l, r);
                        return Ok(t);
                    }
                    Lt => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} < {});", t, l, r);
                        return Ok(t);
                    }
                    Le => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} <= {});", t, l, r);
                        return Ok(t);
                    }
                    Gt => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} > {});", t, l, r);
                        return Ok(t);
                    }
                    Ge => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} >= {});", t, l, r);
                        return Ok(t);
                    }
                    _ => {
                        return Err(e_native("unsupported float operator", span));
                    }
                };
                let _ = writeln!(self.out, "  mno_f64 {} = {}({}, {});", t, fop, l, r);
            }
            (Type::Int, Type::Int, _) | (Type::Bool, Type::Bool, _) => {
                match op {
                    Add => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_iadd({}, {});",
                            t, l, r
                        );
                    }
                    Sub => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_isub({}, {});",
                            t, l, r
                        );
                    }
                    Mul => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_imul({}, {});",
                            t, l, r
                        );
                    }
                    Div => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_idiv({}, {});",
                            t, l, r
                        );
                    }
                    Mod => {
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_irem({}, {});",
                            t, l, r
                        );
                    }
                    Eq => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} == {});", t, l, r);
                    }
                    Ne => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} != {});", t, l, r);
                    }
                    Lt => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} < {});", t, l, r);
                    }
                    Le => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} <= {});", t, l, r);
                    }
                    Gt => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} > {});", t, l, r);
                    }
                    Ge => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} >= {});", t, l, r);
                    }
                    And => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} && {});", t, l, r);
                    }
                    Or => {
                        let _ = writeln!(self.out, "  mno_i64 {} = ({} || {});", t, l, r);
                    }
                }
            }
            _ => {
                return Err(e_native(
                    &format!("native backend: unsupported operands for '{:?}'", op),
                    span,
                ));
            }
        }
        Ok(t)
    }

    fn emit_call(
        &mut self,
        name: &str,
        args: &[Expr],
        _expected: Option<&Type>,
        span: Span,
    ) -> Result<String, Diagnostic> {
        // Host / builtin surface
        match name {
            "print" => {
                let ty = self.type_of(&args[0]);
                let v = self.emit_expr(&args[0], Some(&ty))?;
                match ty {
                    Type::Int => {
                        let _ = writeln!(self.out, "  mno_print_i64({});", v);
                    }
                    Type::Float => {
                        let _ = writeln!(self.out, "  mno_print_f64({});", v);
                    }
                    Type::Bool => {
                        let _ = writeln!(self.out, "  mno_print_bool({});", v);
                    }
                    Type::Str => {
                        let _ = writeln!(self.out, "  mno_print_str({});", v);
                    }
                    _ => {
                        return Err(e_native(
                            "native print only supports int/float/bool/str",
                            span,
                        ));
                    }
                }
                return Ok("0LL".into());
            }
            "len" => {
                let ty = self.type_of(&args[0]);
                let v = self.emit_expr(&args[0], Some(&ty))?;
                let t = self.fresh("len");
                match ty {
                    Type::Str => {
                        let _ = writeln!(self.out, "  mno_i64 {} = mno_str_len({});", t, v);
                    }
                    Type::Array(_) => {
                        let _ = writeln!(self.out, "  mno_i64 {} = mno_arr_len({});", t, v);
                    }
                    _ => return Err(e_native("len expects str or array", span)),
                }
                return Ok(t);
            }
            "push" => {
                let a = self.emit_expr(&args[0], None)?;
                let elem_ty = match self.type_of(&args[0]) {
                    Type::Array(e) => *e,
                    _ => Type::Int,
                };
                let v = self.emit_expr(&args[1], Some(&elem_ty))?;
                let t = self.fresh("push");
                if elem_ty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_f64_to_bits({});",
                        bits, v
                    );
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_arr_push({}, {});",
                        t, a, bits
                    );
                } else {
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_arr_push({}, {});",
                        t, a, v
                    );
                }
                return Ok(t);
            }
            "char_at" => {
                let s = self.emit_expr(&args[0], Some(&Type::Str))?;
                let i = self.emit_expr(&args[1], Some(&Type::Int))?;
                let t = self.fresh("ch");
                let _ = writeln!(self.out, "  mno_i64 {} = mno_str_at({}, {});", t, s, i);
                return Ok(t);
            }
            "substr" => {
                let s = self.emit_expr(&args[0], Some(&Type::Str))?;
                let a = self.emit_expr(&args[1], Some(&Type::Int))?;
                let b = self.emit_expr(&args[2], Some(&Type::Int))?;
                let t = self.fresh("sub");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_substr({}, {}, {});",
                    t, s, a, b
                );
                return Ok(t);
            }
            "chr" => {
                let c = self.emit_expr(&args[0], Some(&Type::Int))?;
                let t = self.fresh("chr");
                let _ = writeln!(self.out, "  mno_i64 {} = mno_chr({});", t, c);
                return Ok(t);
            }
            "len_cp" => {
                let s = self.emit_expr(&args[0], Some(&Type::Str))?;
                let t = self.fresh("lcp");
                let _ = writeln!(self.out, "  mno_i64 {} = mno_len_cp({});", t, s);
                return Ok(t);
            }
            "char_at_cp" => {
                let s = self.emit_expr(&args[0], Some(&Type::Str))?;
                let i = self.emit_expr(&args[1], Some(&Type::Int))?;
                let t = self.fresh("ccp");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_char_at_cp({}, {});",
                    t, s, i
                );
                return Ok(t);
            }
            "substr_cp" => {
                let s = self.emit_expr(&args[0], Some(&Type::Str))?;
                let a = self.emit_expr(&args[1], Some(&Type::Int))?;
                let b = self.emit_expr(&args[2], Some(&Type::Int))?;
                let t = self.fresh("scp");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_substr_cp({}, {}, {});",
                    t, s, a, b
                );
                return Ok(t);
            }
            "chr_cp" => {
                let c = self.emit_expr(&args[0], Some(&Type::Int))?;
                let t = self.fresh("chrp");
                let _ = writeln!(self.out, "  mno_i64 {} = mno_chr_cp({});", t, c);
                return Ok(t);
            }
            "to_int" => {
                let v = self.emit_expr(&args[0], Some(&Type::Float))?;
                let t = self.fresh("toi");
                let _ = writeln!(self.out, "  mno_i64 {} = mno_to_int({});", t, v);
                return Ok(t);
            }
            "to_float" => {
                let v = self.emit_expr(&args[0], Some(&Type::Int))?;
                let t = self.fresh("tof");
                let _ = writeln!(self.out, "  mno_f64 {} = mno_to_float({});", t, v);
                return Ok(t);
            }
            "hash" => {
                let ty = self.type_of(&args[0]);
                let v = self.emit_expr(&args[0], Some(&ty))?;
                let t = self.fresh("h");
                if ty == Type::Str {
                    let _ = writeln!(self.out, "  mno_i64 {} = mno_hash_str({});", t, v);
                } else {
                    let _ = writeln!(self.out, "  mno_i64 {} = {};", t, v);
                }
                return Ok(t);
            }
            "spawn" | "join_int" | "join_float" | "join_bool" | "join_str" | "chan_new"
            | "chan_close" | "chan_send_int" | "chan_send_bool" | "chan_send_float"
            | "chan_send_str" | "chan_recv_int" | "chan_recv_bool" | "chan_recv_float"
            | "chan_recv_str" => {
                return Err(e_native(
                    "native backend: spawn/channels are not yet supported; use machino run or WASM",
                    span,
                ));
            }
            _ => {}
        }

        // Host externs mapped to runtime
        let host = match name {
            "args" => Some(("mno_args", true, Type::Array(Box::new(Type::Str)))),
            "getenv" => Some(("mno_getenv", true, Type::Str)),
            "clock_ms" => Some(("mno_clock_ms", true, Type::Int)),
            "sleep_ms" => Some(("mno_sleep_ms", false, Type::Unit)),
            "read_file" => Some(("mno_read_file", true, Type::Str)),
            "write_file" => Some(("mno_write_file", true, Type::Int)),
            "file_exists" => Some(("mno_file_exists", true, Type::Bool)),
            "read_line" => Some(("mno_read_line", true, Type::Str)),
            "exit" => Some(("mno_exit", false, Type::Unit)),
            "http_get" => Some(("mno_http_get", true, Type::Str)),
            "tcp_listen" => Some(("mno_tcp_listen", true, Type::Int)),
            "tcp_accept" => Some(("mno_tcp_accept", true, Type::Int)),
            "tcp_read" => Some(("mno_tcp_read", true, Type::Str)),
            "tcp_write" => Some(("mno_tcp_write", true, Type::Int)),
            "tcp_close" => Some(("mno_tcp_close", false, Type::Unit)),
            _ => None,
        };
        if let Some((fname, has_ret, ret)) = host {
            let mut arg_ss = Vec::new();
            let param_tys: Option<Vec<Type>> =
                self.signatures.get(name).map(|(ps, _)| ps.clone());
            if let Some(params) = param_tys {
                for (a, p) in args.iter().zip(params.iter()) {
                    arg_ss.push(self.emit_expr(a, Some(p))?);
                }
            } else {
                for a in args {
                    arg_ss.push(self.emit_expr(a, None)?);
                }
            }
            if has_ret {
                let t = self.fresh("call");
                let pt = if ret == Type::Float {
                    "mno_f64"
                } else {
                    "mno_i64"
                };
                let _ = write!(self.out, "  {} {} = {}(", pt, t, fname);
                for (i, a) in arg_ss.iter().enumerate() {
                    if i > 0 {
                        self.out.push_str(", ");
                    }
                    self.out.push_str(a);
                }
                self.out.push_str(");\n");
                return Ok(t);
            } else {
                let _ = write!(self.out, "  {}(", fname);
                for (i, a) in arg_ss.iter().enumerate() {
                    if i > 0 {
                        self.out.push_str(", ");
                    }
                    self.out.push_str(a);
                }
                self.out.push_str(");\n");
                return Ok("0LL".into());
            }
        }

        // Enum variant constructor
        if let Some(colon) = name.rfind("::") {
            let en = &name[..colon];
            let vn = &name[colon + 2..];
            if let Some(variants) = self.enums.get(en).cloned() {
                let (tag, variant) = variants
                    .iter()
                    .enumerate()
                    .find(|(_, v)| v.name == vn)
                    .map(|(i, v)| (i, *v))
                    .ok_or_else(|| e_native("unknown variant", span))?;
                let t = self.fresh("en");
                let _ = writeln!(
                    self.out,
                    "  mno_i64 {} = mno_enum_new({}LL, {}LL);",
                    t,
                    tag,
                    variant.payloads.len()
                );
                for (i, (a, pty)) in args.iter().zip(variant.payloads.iter()).enumerate() {
                    let v = self.emit_expr(a, Some(pty))?;
                    if *pty == Type::Float {
                        let bits = self.fresh("bits");
                        let _ = writeln!(
                            self.out,
                            "  mno_i64 {} = mno_f64_to_bits({});",
                            bits, v
                        );
                        let _ = writeln!(
                            self.out,
                            "  mno_enum_set_payload({}, {}LL, {});",
                            t, i, bits
                        );
                    } else {
                        let _ = writeln!(
                            self.out,
                            "  mno_enum_set_payload({}, {}LL, {});",
                            t, i, v
                        );
                    }
                }
                return Ok(t);
            }
        }

        // Struct constructor
        if let Some(fields) = self.structs.get(name).cloned() {
            let t = self.fresh("st");
            let _ = writeln!(
                self.out,
                "  mno_i64 {} = mno_struct_new({}LL);",
                t,
                fields.len()
            );
            for (i, (fld, a)) in fields.iter().zip(args.iter()).enumerate() {
                let v = self.emit_expr(a, Some(&fld.ty))?;
                if fld.ty == Type::Float {
                    let bits = self.fresh("bits");
                    let _ = writeln!(
                        self.out,
                        "  mno_i64 {} = mno_f64_to_bits({});",
                        bits, v
                    );
                    let _ = writeln!(
                        self.out,
                        "  mno_struct_set({}, {}LL, {});",
                        t, i, bits
                    );
                } else {
                    let _ = writeln!(self.out, "  mno_struct_set({}, {}LL, {});", t, i, v);
                }
            }
            return Ok(t);
        }

        // User / std function
        let (params, ret) = self
            .signatures
            .get(name)
            .cloned()
            .ok_or_else(|| e_native(&format!("unknown function '{}'", name), span))?;
        let mut arg_ss = Vec::new();
        for (a, p) in args.iter().zip(params.iter()) {
            arg_ss.push(self.emit_expr(a, Some(p))?);
        }
        if ret == Type::Unit {
            let _ = write!(self.out, "  {}(", c_ident(name));
            for (i, a) in arg_ss.iter().enumerate() {
                if i > 0 {
                    self.out.push_str(", ");
                }
                self.out.push_str(a);
            }
            self.out.push_str(");\n");
            Ok("0LL".into())
        } else {
            let t = self.fresh("call");
            let pt = if ret == Type::Float {
                "mno_f64"
            } else {
                "mno_i64"
            };
            let _ = write!(self.out, "  {} {} = {}(", pt, t, c_ident(name));
            for (i, a) in arg_ss.iter().enumerate() {
                if i > 0 {
                    self.out.push_str(", ");
                }
                self.out.push_str(a);
            }
            self.out.push_str(");\n");
            Ok(t)
        }
    }

    fn emit_match(
        &mut self,
        m: &Match,
        expected: Option<&Type>,
        span: Span,
    ) -> Result<String, Diagnostic> {
        let sty = self.type_of(&m.scrutinee);
        let s = self.emit_expr(&m.scrutinee, Some(&sty))?;
        let result_ty = expected.cloned().unwrap_or_else(|| {
            m.arms
                .first()
                .map(|a| self.type_of(&a.body))
                .unwrap_or(Type::Int)
        });
        let t = self.fresh("match");
        let pt = if result_ty == Type::Float {
            "mno_f64"
        } else {
            "mno_i64"
        };
        let _ = writeln!(self.out, "  {} {} = 0;", pt, t);
        let end = self.fresh_label("match_end");
        for (i, arm) in m.arms.iter().enumerate() {
            let lbl = self.fresh_label(&format!("arm{}", i));
            let next = self.fresh_label(&format!("next{}", i));
            let _ = writeln!(self.out, "  {{\n    /* match arm */");
            self.push_scope();
            self.emit_pattern_test(&arm.pattern, &s, &sty, &lbl, &next)?;
            let _ = writeln!(self.out, "    {}:;", lbl);
            let v = self.emit_expr(&arm.body, Some(&result_ty))?;
            let _ = writeln!(self.out, "    {} = {};", t, v);
            let _ = writeln!(self.out, "    goto {};", end);
            let _ = writeln!(self.out, "    {}:;", next);
            self.pop_scope();
            self.out.push_str("  }\n");
        }
        let _ = writeln!(
            self.out,
            "  mno_fail(\"runtime error: non-exhaustive match\");"
        );
        let _ = writeln!(self.out, "  {}:;", end);
        let _ = span;
        Ok(t)
    }

    fn emit_pattern_test(
        &mut self,
        pat: &Pattern,
        scrut: &str,
        sty: &Type,
        ok: &str,
        fail: &str,
    ) -> Result<(), Diagnostic> {
        match pat {
            Pattern::Wildcard => {
                let _ = writeln!(self.out, "    goto {};", ok);
            }
            Pattern::Var(name) => {
                let pt = if *sty == Type::Float {
                    "mno_f64"
                } else {
                    "mno_i64"
                };
                let _ = writeln!(self.out, "    {} {} = {};", pt, c_ident(name), scrut);
                self.bind(name, sty.clone());
                let _ = writeln!(self.out, "    goto {};", ok);
            }
            Pattern::Int(n) => {
                let _ = writeln!(
                    self.out,
                    "    if ({} == {}LL) goto {}; else goto {};",
                    scrut, n, ok, fail
                );
            }
            Pattern::Bool(b) => {
                let v = if *b { 1 } else { 0 };
                let _ = writeln!(
                    self.out,
                    "    if ({} == {}LL) goto {}; else goto {};",
                    scrut, v, ok, fail
                );
            }
            Pattern::Str(s) => {
                let lit = self.fresh("plit");
                let _ = writeln!(
                    self.out,
                    "    mno_i64 {} = mno_str_from_lit({}, {}LL);",
                    lit,
                    escape_c_string(s),
                    s.len()
                );
                let _ = writeln!(
                    self.out,
                    "    if (mno_str_eq({}, {})) goto {}; else goto {};",
                    scrut, lit, ok, fail
                );
            }
            Pattern::Variant(en, vn) => {
                let tag = self.variant_tag(en, vn)?;
                let _ = writeln!(
                    self.out,
                    "    if (mno_enum_tag({}) == {}LL) goto {}; else goto {};",
                    scrut, tag, ok, fail
                );
            }
            Pattern::VariantPayload(en, vn, binds) => {
                let tag = self.variant_tag(en, vn)?;
                let variants = self.enums.get(en.as_str()).cloned().unwrap_or_default();
                let variant = variants.iter().find(|v| v.name == *vn).copied();
                let Some(variant) = variant else {
                    return Err(e_native("unknown variant in pattern", Span::new(0, 0)));
                };
                let _ = writeln!(
                    self.out,
                    "    if (mno_enum_tag({}) != {}LL) goto {};",
                    scrut, tag, fail
                );
                for (i, bp) in binds.iter().enumerate() {
                    let pty = variant
                        .payloads
                        .get(i)
                        .cloned()
                        .unwrap_or(Type::Int);
                    let pv = self.fresh("pay");
                    if pty == Type::Float {
                        let bits = self.fresh("bits");
                        let _ = writeln!(
                            self.out,
                            "    mno_i64 {} = mno_enum_payload({}, {}LL);",
                            bits, scrut, i
                        );
                        let _ = writeln!(
                            self.out,
                            "    mno_f64 {} = mno_bits_to_f64({});",
                            pv, bits
                        );
                    } else {
                        let _ = writeln!(
                            self.out,
                            "    mno_i64 {} = mno_enum_payload({}, {}LL);",
                            pv, scrut, i
                        );
                    }
                    match bp {
                        Pattern::Var(name) => {
                            let pt = if pty == Type::Float {
                                "mno_f64"
                            } else {
                                "mno_i64"
                            };
                            let _ = writeln!(
                                self.out,
                                "    {} {} = {};",
                                pt,
                                c_ident(name),
                                pv
                            );
                            self.bind(name, pty);
                        }
                        Pattern::Wildcard => {}
                        _ => {
                            return Err(e_native(
                                "native backend: nested patterns in enum payloads not supported",
                                Span::new(0, 0),
                            ));
                        }
                    }
                }
                let _ = writeln!(self.out, "    goto {};", ok);
            }
        }
        Ok(())
    }

    fn variant_tag(&self, en: &str, vn: &str) -> Result<usize, Diagnostic> {
        let variants = self
            .enums
            .get(en)
            .ok_or_else(|| e_native("unknown enum in pattern", Span::new(0, 0)))?;
        variants
            .iter()
            .position(|v| v.name == vn)
            .ok_or_else(|| e_native("unknown variant", Span::new(0, 0)))
    }

    fn field_index(&self, sname: &str, field: &str, span: Span) -> Result<usize, Diagnostic> {
        let fields = self
            .structs
            .get(sname)
            .ok_or_else(|| e_native("unknown struct", span))?;
        fields
            .iter()
            .position(|f| f.name == field)
            .ok_or_else(|| e_native("unknown field", span))
    }

    fn field_type(&self, sname: &str, field: &str) -> Type {
        self.structs
            .get(sname)
            .and_then(|fs| fs.iter().find(|f| f.name == field))
            .map(|f| f.ty.clone())
            .unwrap_or(Type::Int)
    }

    fn type_of(&self, expr: &Expr) -> Type {
        match &expr.kind {
            ExprKind::Int(_) => Type::Int,
            ExprKind::Float(_) => Type::Float,
            ExprKind::Bool(_) => Type::Bool,
            ExprKind::Str(_) => Type::Str,
            ExprKind::Var(name) => {
                if let Some(t) = self.lookup_ty(name) {
                    return t;
                }
                if let Some(colon) = name.rfind("::") {
                    let en = &name[..colon];
                    if self.enums.contains_key(en) {
                        return Type::Enum(en.to_string());
                    }
                }
                if let Some((params, ret)) = self.signatures.get(name.as_str()) {
                    return Type::Fn(params.clone(), Box::new(ret.clone()));
                }
                Type::Int
            }
            ExprKind::Array(elems) => {
                let e = elems
                    .first()
                    .map(|e| self.type_of(e))
                    .unwrap_or(Type::Int);
                Type::Array(Box::new(e))
            }
            ExprKind::Index(base, _) => match self.type_of(base) {
                Type::Array(e) => *e,
                Type::Str => Type::Int,
                t => t,
            },
            ExprKind::Field(base, field) => match self.type_of(base) {
                Type::Struct(s) => self.field_type(&s, field),
                _ => Type::Int,
            },
            ExprKind::Bin(op, l, r) => {
                use BinOp::*;
                match op {
                    Eq | Ne | Lt | Le | Gt | Ge | And | Or => Type::Bool,
                    Add if matches!(self.type_of(l), Type::Str) => Type::Str,
                    _ => {
                        let lt = self.type_of(l);
                        if lt == Type::Float || self.type_of(r) == Type::Float {
                            Type::Float
                        } else {
                            Type::Int
                        }
                    }
                }
            }
            ExprKind::Un(UnOp::Not, _) => Type::Bool,
            ExprKind::Un(_, inner) => self.type_of(inner),
            ExprKind::Call(name, _, args) => {
                if name == "print" {
                    return Type::Unit;
                }
                if name == "len" || name == "char_at" || name == "to_int" || name == "hash" {
                    return Type::Int;
                }
                if name == "to_float" {
                    return Type::Float;
                }
                if name == "push" {
                    return self.type_of(&args[0]);
                }
                if name == "substr" || name == "chr" || name == "substr_cp" || name == "chr_cp"
                {
                    return Type::Str;
                }
                if let Some((_, ret)) = self.signatures.get(name.as_str()) {
                    return ret.clone();
                }
                if let Some(colon) = name.rfind("::") {
                    return Type::Enum(name[..colon].to_string());
                }
                if self.structs.contains_key(name as &str) {
                    return Type::Struct(name.to_string());
                }
                Type::Int
            }
            ExprKind::Lambda(l) => Type::Fn(
                l.params.iter().map(|p| p.ty.clone()).collect(),
                Box::new(l.ret.clone()),
            ),
            ExprKind::Match(m) => m
                .arms
                .first()
                .map(|a| self.type_of(&a.body))
                .unwrap_or(Type::Int),
        }
    }
}

fn e_native(msg: &str, span: Span) -> Diagnostic {
    Diagnostic::new("E080", msg, span)
        .with_help("the native Clang/LLVM backend does not support this construct yet; use machino run or machino build (WASM)")
}

/// Emit C source for a monomorphized program.
pub fn emit_c(program: &Program) -> Result<String, Diagnostic> {
    // Reject remaining generics
    for f in &program.functions {
        if !f.type_params.is_empty() && !f.is_extern {
            return Err(e_native(
                "internal: generic functions must be monomorphized before native codegen",
                f.span,
            ));
        }
    }
    let mut em = Emitter::new(program);
    em.emit_program()?;
    Ok(em.out)
}

fn runtime_dir() -> PathBuf {
    // Prefer next to the executable, then CARGO_MANIFEST_DIR, then cwd.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let cand = dir.join("../runtime/native");
            if cand.join("machino_rt.c").is_file() {
                return cand.canonicalize().unwrap_or(cand);
            }
            let cand = dir.join("runtime/native");
            if cand.join("machino_rt.c").is_file() {
                return cand.canonicalize().unwrap_or(cand);
            }
        }
    }
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("runtime/native");
    if manifest.join("machino_rt.c").is_file() {
        return manifest;
    }
    PathBuf::from("runtime/native")
}

/// Compile a monomorphized program to a native executable via Clang/LLVM.
pub fn compile_native(program: &Program, out_exe: &Path) -> Result<NativeBuild, Diagnostic> {
    let c_source = emit_c(program)?;
    let rt = runtime_dir();
    let rt_c = rt.join("machino_rt.c");
    let rt_h = rt.join("machino_rt.h");
    if !rt_c.is_file() || !rt_h.is_file() {
        return Err(Diagnostic::new(
            "E080",
            format!(
                "native runtime not found at {} (expected machino_rt.c/h)",
                rt.display()
            ),
            Span::new(0, 0),
        ));
    }

    let work = out_exe
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(format!(
            ".machino-native-{}",
            out_exe
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("out")
        ));
    let _ = std::fs::create_dir_all(&work);
    let c_path = work.join("program.c");
    std::fs::write(&c_path, &c_source).map_err(|e| {
        Diagnostic::new(
            "E080",
            format!("cannot write '{}': {}", c_path.display(), e),
            Span::new(0, 0),
        )
    })?;
    // copy header next to program.c so #include "machino_rt.h" works
    let hdr_dst = work.join("machino_rt.h");
    let _ = std::fs::copy(&rt_h, &hdr_dst);

    let clang = std::env::var("MACHINO_CC").unwrap_or_else(|_| "clang".into());
    let status = Command::new(&clang)
        .args([
            "-O2",
            "-std=c11",
            "-o",
            out_exe.to_str().unwrap_or("a.out"),
            c_path.to_str().unwrap_or("program.c"),
            rt_c.to_str().unwrap_or("machino_rt.c"),
        ])
        .status()
        .map_err(|e| {
            Diagnostic::new(
                "E080",
                format!(
                    "failed to invoke '{}' ({}); install Clang/LLVM or set MACHINO_CC",
                    clang, e
                ),
                Span::new(0, 0),
            )
        })?;
    if !status.success() {
        return Err(Diagnostic::new(
            "E080",
            format!(
                "Clang/LLVM native link failed (exit {}); see compiler diagnostics above",
                status.code().unwrap_or(-1)
            ),
            Span::new(0, 0),
        ));
    }

    // Also emit LLVM IR for the program TU (inspection / tooling).
    let ll_path = work.join("program.ll");
    let ll_status = Command::new(&clang)
        .args([
            "-O2",
            "-std=c11",
            "-S",
            "-emit-llvm",
            "-o",
            ll_path.to_str().unwrap_or("program.ll"),
            c_path.to_str().unwrap_or("program.c"),
            "-I",
            work.to_str().unwrap_or("."),
        ])
        .status();
    let ll_path = match ll_status {
        Ok(s) if s.success() => Some(ll_path),
        _ => None,
    };

    Ok(NativeBuild {
        exe_path: out_exe.to_path_buf(),
        c_path,
        ll_path,
    })
}

fn collect_calls(stmts: &[Stmt], out: &mut HashSet<String>) {
    fn expr(e: &Expr, out: &mut HashSet<String>) {
        match &e.kind {
            ExprKind::Call(name, _, args) => {
                out.insert(name.clone());
                for a in args {
                    expr(a, out);
                }
            }
            ExprKind::Array(xs) => xs.iter().for_each(|x| expr(x, out)),
            ExprKind::Index(a, b) | ExprKind::Bin(_, a, b) => {
                expr(a, out);
                expr(b, out);
            }
            ExprKind::Field(a, _) | ExprKind::Un(_, a) => expr(a, out),
            ExprKind::Match(m) => {
                expr(&m.scrutinee, out);
                for arm in &m.arms {
                    expr(&arm.body, out);
                }
            }
            ExprKind::Lambda(l) => walk_stmts_calls(&l.body, out),
            _ => {}
        }
    }
    fn walk_stmts_calls(stmts: &[Stmt], out: &mut HashSet<String>) {
        for s in stmts {
            match &s.kind {
                StmtKind::Let { value, .. }
                | StmtKind::Assign { value, .. }
                | StmtKind::Assert(value)
                | StmtKind::Expr(value)
                | StmtKind::Return(Some(value)) => expr(value, out),
                StmtKind::IndexAssign {
                    base, index, value, ..
                } => {
                    expr(base, out);
                    expr(index, out);
                    expr(value, out);
                }
                StmtKind::FieldAssign { base, value, .. } => {
                    expr(base, out);
                    expr(value, out);
                }
                StmtKind::If {
                    cond,
                    then_body,
                    else_body,
                } => {
                    expr(cond, out);
                    walk_stmts_calls(then_body, out);
                    walk_stmts_calls(else_body, out);
                }
                StmtKind::While {
                    cond,
                    invariant,
                    body,
                } => {
                    expr(cond, out);
                    if let Some(inv) = invariant {
                        expr(inv, out);
                    }
                    walk_stmts_calls(body, out);
                }
                StmtKind::For {
                    start, end, body, ..
                } => {
                    expr(start, out);
                    expr(end, out);
                    walk_stmts_calls(body, out);
                }
                _ => {}
            }
        }
    }
    walk_stmts_calls(stmts, out);
}

fn reachable_from_main(program: &Program) -> HashSet<String> {
    let mut reachable: HashSet<String> = HashSet::new();
    reachable.insert("main".into());
    let mut queue = vec!["main".to_string()];
    let by_name: HashMap<&str, &Function> = program
        .functions
        .iter()
        .map(|f| (f.name.as_str(), f))
        .collect();
    while let Some(name) = queue.pop() {
        let Some(f) = by_name.get(name.as_str()) else {
            continue;
        };
        let mut calls = HashSet::new();
        collect_calls(&f.body, &mut calls);
        for c in f.requires.iter().chain(f.ensures.iter()) {
            let wrapper = [Stmt {
                kind: StmtKind::Expr(c.expr.clone()),
                span: c.expr.span,
            }];
            collect_calls(&wrapper, &mut calls);
        }
        for c in calls {
            if reachable.insert(c.clone()) {
                queue.push(c);
            }
        }
    }
    reachable
}

/// Collect diagnostics for unsupported constructs in code reachable from main.
pub fn unsupported_constructs(program: &Program) -> Vec<Diagnostic> {
    let mut diags = Vec::new();
    let reachable = reachable_from_main(program);

    fn walk_expr(e: &Expr, diags: &mut Vec<Diagnostic>) {
        match &e.kind {
            ExprKind::Lambda(_) => diags.push(e_native(
                "native backend: lambdas are not yet supported",
                e.span,
            )),
            ExprKind::Call(name, _, args) => {
                if matches!(
                    name.as_str(),
                    "spawn"
                        | "join_int"
                        | "join_float"
                        | "join_bool"
                        | "join_str"
                        | "chan_new"
                        | "chan_close"
                        | "chan_send_int"
                        | "chan_send_bool"
                        | "chan_send_float"
                        | "chan_send_str"
                        | "chan_recv_int"
                        | "chan_recv_bool"
                        | "chan_recv_float"
                        | "chan_recv_str"
                ) {
                    diags.push(e_native(
                        "native backend: spawn/channels are not yet supported",
                        e.span,
                    ));
                }
                for a in args {
                    walk_expr(a, diags);
                }
            }
            ExprKind::Array(xs) => xs.iter().for_each(|x| walk_expr(x, diags)),
            ExprKind::Index(a, b) | ExprKind::Bin(_, a, b) => {
                walk_expr(a, diags);
                walk_expr(b, diags);
            }
            ExprKind::Field(a, _) | ExprKind::Un(_, a) => walk_expr(a, diags),
            ExprKind::Match(m) => {
                walk_expr(&m.scrutinee, diags);
                for arm in &m.arms {
                    walk_expr(&arm.body, diags);
                }
            }
            _ => {}
        }
    }
    fn walk_stmts(stmts: &[Stmt], diags: &mut Vec<Diagnostic>) {
        for s in stmts {
            match &s.kind {
                StmtKind::Let { value, .. }
                | StmtKind::Assign { value, .. }
                | StmtKind::Assert(value)
                | StmtKind::Expr(value)
                | StmtKind::Return(Some(value)) => walk_expr(value, diags),
                StmtKind::IndexAssign {
                    base, index, value, ..
                } => {
                    walk_expr(base, diags);
                    walk_expr(index, diags);
                    walk_expr(value, diags);
                }
                StmtKind::FieldAssign { base, value, .. } => {
                    walk_expr(base, diags);
                    walk_expr(value, diags);
                }
                StmtKind::If {
                    cond,
                    then_body,
                    else_body,
                } => {
                    walk_expr(cond, diags);
                    walk_stmts(then_body, diags);
                    walk_stmts(else_body, diags);
                }
                StmtKind::While {
                    cond,
                    invariant,
                    body,
                } => {
                    walk_expr(cond, diags);
                    if let Some(inv) = invariant {
                        walk_expr(inv, diags);
                    }
                    walk_stmts(body, diags);
                }
                StmtKind::For {
                    start, end, body, ..
                } => {
                    walk_expr(start, diags);
                    walk_expr(end, diags);
                    walk_stmts(body, diags);
                }
                _ => {}
            }
        }
    }
    for f in &program.functions {
        if f.is_extern || !f.type_params.is_empty() || !reachable.contains(&f.name) {
            continue;
        }
        walk_stmts(&f.body, &mut diags);
        for c in f.requires.iter().chain(f.ensures.iter()) {
            walk_expr(&c.expr, &mut diags);
        }
    }
    diags
}
